### ISSUE TITLE
Where is the bulkMakeMkv.jar file?

### ISSUE THREAD

**Issue by phathak** [UnterrainerInformatik/bulkmakemkv#1]
Hi!

I'm sorry for the silly question but I can't find the bulkMakeMkv.jar file to start the program. I'm not sure how to start it. The read me file is really well written but it seems I'm missing something...

Thanks!

**Comment by guFalcon** [comment]
Hi phathak!

I’m sorry but it seems that I’ve missed pushing it.

I now have corrected that. It’s in the ‘target’ directory like I explained in the readme.md file now.

If you’ve any trouble getting it up and running, just mail again.  I’ll be glad to help.

Cu,

Gerald (Psilo)
