### ISSUE TITLE
Using bulk with cron

### ISSUE THREAD

**Issue by phathak** [UnterrainerInformatik/bulkmakemkv#6]
When using bulkmakemkv periodically using cron job (launchd on a mac), the iso files stay in the iso folder after bulk ripped them. Therefore, next time it runs, it keeps trying to rip them. The program should be able to move the files or rename them after ripping as been completed successfully. Another solution would be to build a database of the files bulk as already seen/ripped.

**Comment by guFalcon** [comment]
Or add your rip-target dir to the list of mkv-dirs. That way it recognizes that it has already ripped them.

**Comment by phathak** [comment]
Genius!

**Comment by guFalcon** [comment]
_ggggggg_
I'm flattered :)
But maybe I will be adding the output-dir automatically since it's never a good idea to leave that one out.

thx
